sprint 9/ FilmController UserController, валидация параметров POJO
rrtuyu/java-filmorate pull request #2
Opened 2023-05-03 12:56 UTC by rrtuyu

Базовая логика для контроллеров Film и User, пока не уверен, что стоило делегировать часть валидации полей в сервисные классы, но другого выхода в голову не пришло.

2023-05-04 21:40 UTC, alexache requested changes

2023-05-08 17:59 UTC, rrtuyu commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getReleaseDate() != null && film.getReleaseDate().isBefore(MIN_RELEASE_DATE)) {
Усложняет процесс тестирования, к сожалени, пока не знаю, как тестить спринг контроллеры без усложнений. Прочитал про mockito, но понял, что залез далековато, в таком случае придется довериться тестам в постмане

2023-05-08 18:00 UTC, rrtuyu commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        this.service = new FilmService();
Добавил анотацию @Service над сервисными, исправил конструктор контроллера

2023-05-08 18:01 UTC, rrtuyu commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getId() == 0) {
Теперь эта проверка находится в в сервисном классе в методе private void checkId()

2023-05-11 20:10 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getReleaseDate() != null && film.getReleaseDate().isBefore(MIN_RELEASE_DATE)) {
Можно воспринимать класс контроллера как обычный класс, создавать его экземпляр и вызывать методы с нужными аргументами. Мокито слишком еще рано

2023-05-11 20:13 UTC, alexache approved these changes

2023-05-12 07:40 UTC, merged