Add friends likes
rrtuyu/java-filmorate pull request #3
Opened 2023-05-19 21:40 UTC by rrtuyu

Расширен функционал: 
- система друзей для пользователей
- система лайков для фильмов
- выборка фильмов по популярности

2023-05-20 19:48 UTC, alexache requested changes

2023-05-20 19:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        this.usersWhoLikedFilm.add(userId);
Зачем использовать this? разве есть пересечения по области видимости с каким-то другими переменными?

2023-05-20 19:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (result.isPresent()) {
Почему бы использоваться для Optional.orElseThrow? И для самого стораджа тогда логично возвращать Optional, а не оборачивать внутри сервиса

2023-05-20 19:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return films.containsValue(film);
Если film.equals включает только справнение по айди, то зачем полный поиск по значениям мапы, а не простой поиск по ключу-айди?

2023-05-20 19:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private static final Map<Integer, User> users = new HashMap<>();
static точно лишнее, зачем это? Спринг и так не будет создавать много объектов стораджа

2023-05-21 01:06 UTC, rrtuyu commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private static final Map<Integer, User> users = new HashMap<>();
Очень круто, спасибо, что открыли глаза! Я думал, что спринг отдаст новый инстанс стораджа филмсервису... Недостаточно углубился в логику внедрения зависимостей :(

2023-05-21 01:31 UTC, rrtuyu commented
Надеюсь, ничего не упустил. Я бы еще заставил User getUser(Integer id) в UserStorage возвращать Optional<User> , но пока сомневаюсь, не усложнит ли это работу UserService и дальнейшее развитие приложения.

2023-05-21 18:25 UTC, alexache approved these changes

2023-05-21 19:28 UTC, merged