Add database
rrtuyu/java-filmorate pull request #8
Opened 2023-06-11 17:22 UTC by rrtuyu

На мой взгляд в этот раз получилось очень криво, буду рад усиленной критике

2023-06-12 19:06 UTC, alexache requested changes

2023-06-12 19:06 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/UserDbStorage.java
> +            user.setId(generatedId); // костыль, надо было заставить возвращать этот метод объект юзера на прошлом тз
Почему же костыль?

2023-06-14 19:15 UTC, rrtuyu commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +            film.setMpa(ratingDao.getById(mpaId).get());
в запросе передается только ID рейтинга, можно оставить только его, но тогда ответом будед некрасивый, поля с именем и описанием будут null :(
конечно, можно обойтись и без этого

2023-06-14 23:17 UTC, rrtuyu commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +                .mpa(ratingDao.getById(ratingId).get())
было нелегко додуматься по неопытности, как это сделать, но что-то вроде получилось. спасибо, опыть очень ценный, теперь буду планировать такие вещи заранее

2023-06-14 23:17 UTC, rrtuyu commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +        film.getGenres().forEach(g -> genreDao.applyGenre(film.getId(), g.getId()));
надеюсь, удалось воплотить именно то, что требовалось

2023-06-14 23:19 UTC, rrtuyu commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +                .mpa(ratingDao.getById(ratingId).get())
а что самое главное, теперь я знаю, как точно делать больше не буду... целых 2 раза

2023-06-14 23:20 UTC, rrtuyu commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/UserDbStorage.java
> +            user.setId(generatedId); // костыль, надо было заставить возвращать этот метод объект юзера на прошлом тз
беру свои слова назад, это еще не костыль :)

2023-06-15 18:56 UTC, alexache requested changes

2023-06-15 22:03 UTC, rrtuyu commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +        Map<Integer, Collection<Integer>> likes = likeDao.getFIlmLikesMap();
тесты это не проверяют, уберу из логики стораджа, но пока оставлю это поле в модели на всякий случай, надеюсь, простительно

2023-06-16 18:24 UTC, alexache approved these changes

2023-06-16 18:43 UTC, merged